package salvo.salvo;

public enum GameState {
    WAIT_FOR_OPPONENT,
    PLACESHIPS,
    WAITING_FOR_OPPONENT_TO_PLACE_SHIPS,
    PLACESALVOS,
    WAIT_FOR_OPPONENT_TO_PLACE_SALVOS,
    GAMEOVER_LOSE,
    GAMEOVER_WIN,
    GAMEOVER_TIE
}
